apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: devops-app
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:postgres@postgres-service:5432/appdb"
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "minioadmin"